#!/bin/bash

set -e -x

#first off, make sure we compile
go test -c
rm vizzini.test

DEV_GOPATH=$HOME/go
STAGING_AREA=/tmp/vizzini

REPOS="
  github.com/cloudfoundry-incubator/vizzini
  github.com/cloudfoundry-incubator/auctioneer
  github.com/cloudfoundry-incubator/route-emitter
  github.com/cloudfoundry/gorouter
  github.com/cloudfoundry-incubator/executor
  github.com/cloudfoundry-incubator/converger
  github.com/cloudfoundry-incubator/rep
  github.com/cloudfoundry-incubator/stager
  github.com/cloudfoundry-incubator/app-manager
  github.com/cloudfoundry-incubator/nsync
  github.com/cloudfoundry-incubator/file-server
  github.com/cloudfoundry-incubator/linux-circus
  github.com/cloudfoundry-incubator/warden-linux
  github.com/cloudfoundry-incubator/tps
"

mkdir -p ${STAGING_AREA}
cp $(dirname $0)/build.yml ${STAGING_AREA}/build.yml

pushd $STAGING_AREA
  # make sure we have all our dependencies (any version)
  go get $(for repo in $REPOS; do echo -n " $repo/..."; done)

  # pull in their packages into the temporary gopath, using godep so that
  # it'll only fetch the packages that are used (not entire repos)
  godep save $(for repo in $REPOS; do echo -n " $repo/..."; done)
  rsync --del --exclude '.*' -a Godeps/_workspace/src/ src/
  rm -rf Godeps
popd

function copy_to_gopath {
  mkdir -p ${STAGING_AREA}/src/${1}
  rsync --del --exclude '.*' --exclude '*.test' -a ${DEV_GOPATH}/src/${1}/ ${STAGING_AREA}/src/${1}/
}

# grab and set up our components
for package in $REPOS; do
  copy_to_gopath $package &
done

# install application dependencies
for package in github.com/coreos/etcd github.com/apcera/gnatsd; do
  copy_to_gopath $package &
done

rsync --del --exclude '.*' -a ~/workspace/loggregator/ ${STAGING_AREA}/loggregator/ &

wait

cd $STAGING_AREA

fly -- bogus-argv-0 "$@"
