#!/bin/bash

set -e -x

export GOROOT=/usr/local/go
export PATH=${GOROOT}/bin:${PATH}

export GOPATH_ROOT=$PWD

export GOPATH=${GOPATH_ROOT}
export PATH=${GOPATH_ROOT}/bin:${PATH}

# set up compile-time $GOPATHs for each component
export LOGGREGATOR_GOPATH=${GOPATH_ROOT}/loggregator
export EXECUTOR_GOPATH=${GOPATH_ROOT}
export AUCTIONEER_GOPATH=${GOPATH_ROOT}
export CONVERGER_GOPATH=${GOPATH_ROOT}
export REP_GOPATH=${GOPATH_ROOT}
export STAGER_GOPATH=${GOPATH_ROOT}
export APP_MANAGER_GOPATH=${GOPATH_ROOT}
export FILE_SERVER_GOPATH=${GOPATH_ROOT}
export WARDEN_LINUX_GOPATH=${GOPATH_ROOT}
export ROUTE_EMITTER_GOPATH=${GOPATH_ROOT}
export ROUTER_GOPATH=${GOPATH_ROOT}
export LINUX_CIRCUS_GOPATH=${GOPATH_ROOT}
export TPS_GOPATH=${GOPATH_ROOT}
export NSYNC_GOPATH=${GOPATH_ROOT}

# install application dependencies
for package in github.com/coreos/etcd github.com/apcera/gnatsd; do
  go install $package
done

pushd $GOPATH_ROOT/src/github.com/cloudfoundry-incubator/warden-linux
  make # compile wshd/etc.
  export WARDEN_BINPATH=$PWD/linux_backend/bin
popd

go install github.com/onsi/ginkgo/ginkgo

export WARDEN_ROOTFS=/opt/warden/rootfs

# used for routing to apps; same logic that Warden uses.
export EXTERNAL_ADDRESS=$(ip route get 8.8.8.8 | sed 's/.*src\s\(.*\)\s/\1/;tx;d;:x')

pushd $GOPATH_ROOT/src/github.com/cloudfoundry-incubator/vizzini
    ginkgo -r -failOnPending -randomizeAllSpecs -trace -v -slowSpecThreshold=10 "$@"
popd
